services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres
    networks:
      - backend
    env_file:
      - /.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis
    networks:
      - backend


networks:
  backend:
    external: false