# Generated by Django 4.2 on 2024-10-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_likes',
            field=models.IntegerField(default=0, verbose_name='количество лайков'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recommendations/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
